### ISSUE TITLE
new project parameter

### ISSUE THREAD

**Issue by BjoernSteinborn78** [adamcbrewer/fireshell#7]
Folowing line in gruntfile.js

`var target = target || "new-project";`

has to be changed to;

`var target = grunt.option('target') || "new-project";`

hasn't it?

**Comment by adamcbrewer** [comment]
Hey @bstei, sorry for the late reply. Yeah, I decided to opt in for task arguments, rather than dashed options. so instead of `grunt new --target="some_dir"` you'll be simply doing: `grunt new:"some_dir"`

**Comment by bstei** [comment]
Hey,

okay, makes sense.

Thanks for the clarification.
